name: "Zeet Deploy"
description: "Deploy your Project with Zeet"
author: "Zeet"
inputs:
  api_url:
    description: "Zeet API Url"
    required: false
  deploy_key:
    description: "Zeet deploy key"
    required: true
  project:
    description: "Zeet project name"
    required: false
  project_id:
    description: "Zeet project id"
    required: false
  image:
    description: "Docker image to deploy"
    required: false
  branch:
    description: "Branch name"
    required: false
  wait:
    description: "Wait till the deploy finishes"
    required: false
    default: "false"
outputs:
  link:
    value: "test"
    description: "Link to deployment"
runs:
  using: "composite"
  steps:
    - name: Install Zeet CLI
      uses: zeet-dev/action-zeet@main
      with:
        token: ${{ inputs.deploy_key }}
        api_url: ${{ inputs.api_url }}
