name: "Zeet Deploy"
description: "Deploy your Project with Zeet"
author: "Zeet"
inputs:
  api_url:
    description: "Zeet API Url"
    required: false
  deploy_key:
    description: "Zeet deploy key"
    required: true
  project_id:
    description: "Zeet project id"
    required: true
  image:
    description: "Docker image to deploy"
    required: false
  branch:
    description: "Git branch to deploy"
    required: false
outputs:
  link:
    description: "Link to deployment"
runs:
  using: "node12"
  main: "dist/index.js"
