name: "Zeet Deploy"
description: "Deploy your Project with Zeet"
author: "Zeet"
inputs:
  api_url:
    description: "Zeet API Url"
    required: false
  deploy_key:
    description: "Zeet deploy key"
    required: true
  project:
    description: "Zeet project name"
    required: false
  project_id:
    description: "Zeet project id"
    required: false
  image:
    description: "Docker image to deploy"
    required: false
  branch:
    description: "Branch name"
    required: false
  wait:
    description: "Wait till the deploy finishes"
    required: false
    default: "false"
outputs:
  link:
    value: "test"
    description: "Link to deployment"
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        repository: zeet-co/zeet-deploy-action
        branch: v2
    - uses: zeet-dev/action-zeet@main
      with:
        token: ${{ inputs.deploy_key }}
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
      shell: bash
    - id: main
      run: node dist/index.js
      shell: bash
      env:
        API_URL: ${{ inputs.api_url}}
        DEPLOY_KEY: ${{ inputs.deploy_key }}
        PROJECT: ${{ inputs.project }}
        PROJECT_ID: ${{ inputs.project_id }}
        IMAGE: ${{ inputs.image }}
        BRANCH: ${{ inputs.branch }}
        WAIT: ${{ inputs.wait }}

